# custom auditbeat.yml config

auditbeat.modules:

- module: auditd
  # Load audit rules from separate files. Same format as audit.rules(7).
  audit_rule_files: [ '${path.config}/audit.rules.d/*.conf' ]
  audit_rules: |

- module: file_integrity
  paths:
  - /bin
  - /usr/bin
  - /sbin
  - /usr/sbin
  - /etc

- module: system
  datasets:
    - package
  period: 2m

- module: system
  datasets:
    - host
    - login
    - process
    - socket
    - user
  state.period: 12h

  user.detect_password_changes: true

setup.template.settings:
  index.number_of_shards: 1

output.file:
  path: "/tmp/auditbeat"
  filename: auditbeat

logging.to_syslog: true






  
