---
- hosts: rocky
  become: yes
  become_method: su
  vars:
    doc_root: /home/packer
    ansible_become_password: root
    network_connections:
       - name: ens192
         interface_name: ens192
         type: ethernet
         autoconnect: yes
         ip:
           address:
             - 192.168.3.152/24
           gateway: 192.168.3.1
           dns:
             - 8.8.8.8  
         state: up
    gather_facts: no
 
  tasks:
    - name: Set default gateway
      community.general.nmcli:
        conn_name: ens192
#        ifname: eth0
        type: ethernet
        ip4: 192.168.3.152/24
        gw4: 192.168.3.1
        state: present
 
    - name: Apply Network Changes
      reboot:
#        test_command: ping -c 192.168.3.192
        reboot_timeout: 60

      #command: >
        #3nmcli con down ens192; nmcli con up ens192

    - name: Install yum-utils
      yum:
        name: yum-utils
        state: latest    
 
    - name: Add HashiCorp repo
      command: >
        sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
      changed_when: false

    - name: Install Packer
      yum:
        name: 
          - packer
          - terraform
          - epel-release
        state: present

    - name: Install Terraform
      yum:
        name: ansible
        state: present

    - name: Create custom document root
      file: path={{ doc_root }} state=directory owner=packer group=packer
    - name: Set up automation files
      ansible.builtin.unarchive: 
        src: "share/automation.zip"
        dest: "{{ doc_root }}/"
