---
- hosts: ubuntu
  become: yes
  vars:
    doc_root: /var/www/html
    ansible_become_password: packer
  gather_facts: no

#Install/update software/packages
  tasks:
    - name: Update apt
      vars: 
        ansible_python_interpreter: /usr/bin/python3
      apt: update_cache=yes  
    - name: Install required software/packages
      vars: 
        ansible_python_interpreter: /usr/bin/python3
      apt:
        pkg:
          - python-minimal
          - python-pip
          - apache2
          - php
          - libapache2-mod-php
          - php-mcrypt
          - php7.0-mysql
          - python-dev
          - libmysqlclient-dev
          - mysql-server
          - unzip
          - auditd
          - audispd-plugins
          - vim
          - tmux
          - curl
          # falco
          - dkms
          - make
        state: latest
        update_cache: true
    - name: Install MySQL-python
      pip: name=MySQL-python  state=present

#Falco logging
    - name: Set up falco logging
      command: |
        curl -fsSLk https://falco.org/repo/falcosecurity-packages.asc | gpg --dearmor -o /usr/share/keyrings/falco-archive-keyring.gpg
        echo “deb [signed-by=/usr/share/keyrings/falco-archive-keyring.gpg] https://download.falco.org/packages/deb stable main” | tee /etc/apt/sources.list.d/falcosecurity.list
        apt update -y
        apt install -qqy falco

#Setup syslog logging
    - name: Set up rsyslog conf file
      copy: src=share/02-apache2.conf dest=/etc/rsyslog.d/
    - name: Restart rsyslog
      service: 
        name: rsyslog
        state: restarted

#Auditbeat logging
    - name: Preparing rsyslog.conf for Auditbeat (commenting out $PrivDrop*)
      command: >
        sed -i '/^\$PrivDrop/s/^/#/' /etc/rsyslog.conf

#Setup auditd logging
    #Delete existing auditd rule files
    - name: Delete existing auditd rules file
      file:
        dest: /etc/audit/audit.rules
        state: absent
    - name: Delete existing auditd rules file
      file:
        dest: /etc/audit/audit.rules
        state: absent
    #Import rule files
    - name: Set up auditd rules file
      copy: src=share/audit.rules dest=/etc/audit/
    - name: Set up auditd rules file
      copy: src=share/audit.rules dest=/etc/audit/rules.d
    - name: Set up auditd config file
      copy: src=share/40-audispd.conf dest=/etc/rsyslog.d/
    - name: Configure auditd to syslog
      command: >
        sudo sed -i 's/^active.*/active = yes/g' /etc/audisp/plugins.d/syslog.conf
    - name: Restart auditd
      service: 
        name: auditd
        state: restarted
    - name: Restart rsyslog
      service:
        name: rsyslog
        state: restarted

#Launch LAMP-app
    - name: Create Apache-app root
      file: path={{ doc_root}} state=directory owner=packer group=packer
    - name: Set up HTML file
      ansible.builtin.unarchive: 
        src: "share/webapp.zip"
        dest: "{{ doc_root}}/"   
    - name: Start up the mysql service
      shell: "service mysql start"
    - name: Ensure mysql is enabled to run on startup
      service: name=mysql state=started enabled=true     
    #login_password is '' on first script run, packer on subsequent
    - name: Update mysql root password for all root accounts
      mysql_user:
        login_user: root
        login_password: packer
        login_host: localhost
        name: root
        password: packer
        check_implicit_admin: yes
        priv: '*.*:ALL,GRANT'
        login_unix_socket: /var/run/mysqld/mysqld.sock
    - name: Create a new database
      mysql_db: name=shoppingcart state=present login_user=root login_password=packer 
    - name: Create database
      copy: src=share/shoppingcart.sql dest=/tmp/shoppingcart.sql
    - name: Insert data into databse
      mysql_db: name=shoppingcart state=import target=/tmp/shoppingcart.sql login_user=root login_password=packer    
      ignore_errors: true
    - name: Restart apache
      service: 
        name: apache2
        state: restarted
