---
- hosts: ubuntu
  become: yes
  vars:
    doc_root: /var/www/html
    ansible_become_password: packer
  gather_facts: no
  tasks:
    - name: Update apt
      vars: 
        ansible_python_interpreter: /usr/bin/python3
      apt: update_cache=yes  
      
#Install/Update software/packages    
    - name: Install required apache and mysql packages
      vars: 
        ansible_python_interpreter: /usr/bin/python3
      apt:
        pkg:
          - python-minimal
          - python-pip
          - apache2
          - php
          - libapache2-mod-php
          - php-mcrypt
          - php7.0-mysql
          - python-dev
          - libmysqlclient-dev
          - mysql-server
          - unzip
        state: latest
        update_cache: true
    - name: Install MySQL-python
      pip: name=MySQL-python  state=present

#Setup syslog logging
    - name: Set up rsyslog conf file
      copy: src=share/02-apache2.conf dest=/etc/rsyslog.d/
      notify:
      - restart rsyslog

#Launch LAMP-app
    - name: Create Apache-app root
      file: path={{ doc_root}} state=directory owner=packer group=packer
    - name: Set up HTML file
      ansible.builtin.unarchive: 
        src: "share/webapp.zip"
        dest: "{{ doc_root}}/"
      notify:
      - restart apache    
    - name: start up the mysql service
      shell: "service mysql start"
    - name: ensure mysql is enabled to run on startup
      service: name=mysql state=started enabled=true     
    #login_password is '' on first script run, packer on subsequent
    - name: update mysql root password for all root accounts
      mysql_user:
        login_user: root
        login_password: packer
        login_host: localhost
        name: root
        password: packer
        check_implicit_admin: yes
        priv: '*.*:ALL,GRANT'
        login_unix_socket: /var/run/mysqld/mysqld.sock
      notify:
      - restart apache
    - name: create a new database
      mysql_db: name=shoppingcart state=present login_user=root login_password=packer 
    - name: create database
      copy: src=share/shoppingcart.sql dest=/tmp/shoppingcart.sql
    - name: insert data into databse
      mysql_db: name=shoppingcart state=import target=/tmp/shoppingcart.sql login_user=root login_password=packer    
      ignore_errors: true
      notify:
      - restart apache

  handlers:
    - name: restart rsyslog
      service: name=rsyslog state=restarted
    - name: restart apache
      service: name=apache2 state=restarted
