---
- hosts: ubuntu
  become: yes
  vars:
    doc_root: /var/www/html
    ansible_become_password: packer
  tasks:
    - name: Update apt
      apt: update_cache=yes
   
    - name: Install Apache
      apt: name=apache2 state=latest

    - name: Create custom document root
      file: path={{ doc_root}} state=directory owner=packer group=packer

    - name: Set up HTML file
      copy: src=index.html dest={{ doc_root}}/index.html owner=packer group=packer mode=0644

  handlers:
    - name: restart apache
      service: name=apache2 state=restarted